# Generated by Django 3.2.13 on 2022-05-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OMC23Nivel1',
            fields=[
                ('idOmc23N1', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N1')),
                ('Codigo', models.CharField(max_length=10)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Omc23Nivel1',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel2',
            fields=[
                ('idOmc23N2', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N2')),
                ('Codigo', models.CharField(max_length=10)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=110, null=True)),
                ('fk_Omc23N1', models.ForeignKey(db_column='fk_Omc23N1', on_delete=django.db.models.deletion.CASCADE, to='ProyectoDemoCostosApp.omc23nivel1', verbose_name='Nivel 1')),
            ],
            options={
                'db_table': 'Omc23Nivel2',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel3',
            fields=[
                ('idOmc23N3', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N3')),
                ('Codigo', models.CharField(max_length=10)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_Omc23N2', models.ForeignKey(db_column='fk_Omc23N2', on_delete=django.db.models.deletion.CASCADE, to='ProyectoDemoCostosApp.omc23nivel2', verbose_name='Nivel 2')),
            ],
            options={
                'db_table': 'Omc23Nivel3',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel4',
            fields=[
                ('idOmc23N4', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N4')),
                ('Codigo', models.CharField(max_length=15)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=110, null=True)),
                ('fk_Omc23N3', models.ForeignKey(db_column='fk_Omc23N3', on_delete=django.db.models.deletion.CASCADE, to='ProyectoDemoCostosApp.omc23nivel3', verbose_name='Nivel 3')),
            ],
            options={
                'db_table': 'Omc23Nivel4',
            },
        ),
        migrations.CreateModel(
            name='OMC23Nivel5',
            fields=[
                ('idOmc23N5', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N5')),
                ('Codigo', models.CharField(max_length=15)),
                ('descriEng', models.CharField(max_length=120)),
                ('descriSpa', models.CharField(blank=True, max_length=120, null=True)),
                ('fk_Omc23N4', models.ForeignKey(db_column='fk_Omc23N4', on_delete=django.db.models.deletion.CASCADE, to='ProyectoDemoCostosApp.omc23nivel4', verbose_name='Nivel 4')),
            ],
            options={
                'db_table': 'Omc23Nivel5',
            },
        ),
        migrations.CreateModel(
            name='OmniClass23',
            fields=[
                ('idOmc23', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23')),
                ('noMat', models.IntegerField()),
                ('Codigo', models.CharField(max_length=18)),
                ('descriEng', models.CharField(blank=True, max_length=120, null=True)),
                ('descriSpa', models.CharField(blank=True, max_length=120, null=True)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OMC23Nivel6',
            fields=[
                ('idOmc23N6', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23N6')),
                ('Codigo', models.CharField(max_length=18)),
                ('descriEng', models.CharField(max_length=100)),
                ('descriSpa', models.CharField(blank=True, max_length=100, null=True)),
                ('fk_Omc23N5', models.ForeignKey(db_column='fk_Omc23N5', on_delete=django.db.models.deletion.CASCADE, to='ProyectoDemoCostosApp.omc23nivel5', verbose_name='Nivel 5')),
            ],
            options={
                'db_table': 'Omc23Nivel6',
            },
        ),
    ]
