# Generated by Django 3.2.13 on 2022-05-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoDemoCostosApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='omniclass23',
            old_name='nivel',
            new_name='Nivel',
        ),
        migrations.AlterModelTable(
            name='omniclass23',
            table='Omniclass23',
        ),
    ]
